name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test-sast:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('app/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r app/requirements.txt

      - name: Start application
        run: |
          uvicorn app.src.main:app --host 0.0.0.0 --port 8000 &
          sleep 5

      - name: Healthcheck application
        run: |
          curl --retry 5 --retry-delay 3 --retry-connrefused http://localhost:8000/health

      - name: Run tests with coverage
        run: pytest app/tests/ --cov=app --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true

      - name: Build Docker image
        run: docker build -t myapp:latest app/

      - name: CodeQL init
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: CodeQL analyze
        uses: github/codeql-action/analyze@v3
