name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r app/requirements.txt

      - name: Start application
        run: |
          uvicorn app.src.main:app --host 0.0.0.0 --port 8000 &
          sleep 5

      - name: Run tests with coverage
        run: pytest app/tests/ --cov=app --cov-report=html --cov-report=term

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov/

      - name: Build Docker image
        run: docker build -t myapp:latest app/
