name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test-sast:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r app/requirements.txt

      - name: Start application
        run: |
          uvicorn app.src.main:app --host 0.0.0.0 --port 8000 &
          sleep 5

      - name: Run tests
        run: pytest app/tests/

      - name: Build Docker image
        run: docker build -t myapp:latest app/

      - name: CodeQL init
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: CodeQL analyze
        uses: github/codeql-action/analyze@v3
